# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  aws:
    name: AWS Terraform (OIDC)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/aws

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654557743:role/terraform-git-ci-role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

  gcp:
    name: GCP Terraform (OIDC / Workload Identity)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/gcp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to GCP using workload identity federation
      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/272310448946/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-github-actions@cert-enroll-demo-prj.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
